server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${muscle-grow.datasource.driver-class-name}
      url: jdbc:mysql://${muscle-grow.datasource.host}:${muscle-grow.datasource.port}/${muscle-grow.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${muscle-grow.datasource.username}
      password: ${muscle-grow.datasource.password}
  redis:
    host: ${musclegrow.redis.host}
    port: ${musclegrow.redis.port}
    password: ${musclegrow.redis.password}
    database: ${musclegrow.redis.database}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.musclegrow.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com:
      musclegrow:
        mapper: debug
        service: info
        controller: info

muscle-grow:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: muscle-grow-user
    user-ttl: 7200000
    user-token-name: authentication

  alioss:
    endpoint: ${muscle-grow.alioss.endpoint}
    access-key-id: ${muscle-grow.alioss.access-key-id}
    access-key-secret: ${muscle-grow.alioss.access-key-secret}
    bucket-name: ${muscle-grow.alioss.bucket-name}
